module.exports.data = [
  {name: 'abatacept', sizePrices: ['250/345.34']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
  {name: '', sizePrices: ['']},
]
