module.exports.data = [
  {name: 'abatacept', sizePrices: ['250/345.34']},
  {name: 'bevacizumab', sizePrices: ['100/536.49', '400/2145.58']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
  // {name: '', sizePrices: ['']},
]
